spring:
  datasource:
    url: jdbc:postgresql://54.172.231.196:5432/postgres    username: docker
    password: docker
  liquibase:
    enabled: false
    change-log: classpath:/db-changelog/changelog-master.yml      jpa:    hibernate:      ddl-auto: update    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true  jackson:    serialization:      write-dates-as-timestamps: false
kafka:
   bootstrap-servers:  54.152.71.186:9092   
   topic:
      avro: 
        customer: customer-topic 
        user: user-topic 