spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/postgres    username: docker
    password: docker
  liquibase:
    enabled: false
    change-log: classpath:/db-changelog/changelog-master.yml      jpa:    hibernate:      ddl-auto: create-drop    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true      