spring:
  datasource:
    url: jdbc:postgresql://54.89.158.139:5432/postgres    username: docker
    password: docker
  liquibase:
    enabled: false
    change-log: classpath:/db-changelog/changelog-master.yml      jpa:    hibernate:      ddl-auto: update    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true  jackson:    serialization:      write-dates-as-timestamps: false
kafka:
   bootstrap-servers: 18.232.87.26:9092  
   topic:
      avro: 
        customer: customer-topic 
        user: user-topic 